// SPDX-License-Identifier: MIT
package worker

import (
	"context"
	"fmt"

	"github.com/sirupsen/logrus"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

var log = logrus.New()

// Service implements the WorkerService gRPC interface
type Service struct {
	UnimplementedWorkerServiceServer
	pool *Pool
}

// NewService creates a new worker service
func NewService(pool *Pool) *Service {
	return &Service{
		pool: pool,
	}
}

// Register handles worker registration
func (s *Service) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	if req.WorkerId == "" {
		return nil, status.Error(codes.InvalidArgument, "worker_id is required")
	}

	if req.Capabilities == nil {
		return nil, status.Error(codes.InvalidArgument, "capabilities are required")
	}

	sessionToken, err := s.pool.Register(req.WorkerId, req.Capabilities)
	if err != nil {
		return &RegisterResponse{
			Success: false,
			Message: err.Error(),
		}, nil
	}

	log.Infof("Worker %s registered successfully", req.WorkerId)

	return &RegisterResponse{
		Success:      true,
		Message:      "Registration successful",
		SessionToken: sessionToken,
	}, nil
}

// Heartbeat handles worker heartbeat
func (s *Service) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error) {
	if req.WorkerId == "" || req.SessionToken == "" {
		return nil, status.Error(codes.InvalidArgument, "worker_id and session_token are required")
	}

	if req.Status == nil {
		return nil, status.Error(codes.InvalidArgument, "status is required")
	}

	err := s.pool.UpdateHeartbeat(req.WorkerId, req.SessionToken, req.Status)
	if err != nil {
		return nil, status.Error(codes.Unauthenticated, err.Error())
	}

	return &HeartbeatResponse{
		Acknowledged: true,
	}, nil
}

// GetJob assigns a job to a worker
func (s *Service) GetJob(ctx context.Context, req *GetJobRequest) (*GetJobResponse, error) {
	if req.WorkerId == "" || req.SessionToken == "" {
		return nil, status.Error(codes.InvalidArgument, "worker_id and session_token are required")
	}

	// TODO: Implement actual job assignment logic
	// For PoC, return no job available
	return &GetJobResponse{
		HasJob: false,
	}, nil
}

// ReportResult handles job result reporting
func (s *Service) ReportResult(ctx context.Context, req *ReportResultRequest) (*ReportResultResponse, error) {
	if req.WorkerId == "" || req.SessionToken == "" {
		return nil, status.Error(codes.InvalidArgument, "worker_id and session_token are required")
	}

	if req.Result == nil {
		return nil, status.Error(codes.InvalidArgument, "result is required")
	}

	// TODO: Validate worker session and process result
	// For PoC, always accept
	log.Infof("Worker %s reported result for job %d", req.WorkerId, req.JobId)

	return &ReportResultResponse{
		Accepted: true,
		Message:  fmt.Sprintf("Result for job %d accepted", req.JobId),
	}, nil
}

// Additional helper for gRPC code generation
// RegisterWorkerServiceServer is generated by protoc
// UnimplementedWorkerServiceServer is generated by protoc