// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: src/worker/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Capabilities  *WorkerCapabilities    `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_src_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() *WorkerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type WorkerCapabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobTypes          []string               `protobuf:"bytes,1,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"` // ["ATTACK", "DEFENSE"]
	MaxConcurrentJobs uint32                 `protobuf:"varint,2,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	CpuCores          uint32                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb          uint64                 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkerCapabilities) Reset() {
	*x = WorkerCapabilities{}
	mi := &file_src_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapabilities) ProtoMessage() {}

func (x *WorkerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapabilities.ProtoReflect.Descriptor instead.
func (*WorkerCapabilities) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerCapabilities) GetJobTypes() []string {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

func (x *WorkerCapabilities) GetMaxConcurrentJobs() uint32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *WorkerCapabilities) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *WorkerCapabilities) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_src_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Status        *WorkerStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_src_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *WorkerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type WorkerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveJobs    uint32                 `protobuf:"varint,1,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	CompletedJobs uint32                 `protobuf:"varint,2,opt,name=completed_jobs,json=completedJobs,proto3" json:"completed_jobs,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float32                `protobuf:"fixed32,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_src_worker_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerStatus) GetActiveJobs() uint32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerStatus) GetCompletedJobs() uint32 {
	if x != nil {
		return x.CompletedJobs
	}
	return 0
}

func (x *WorkerStatus) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *WorkerStatus) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_src_worker_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type GetJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionToken   string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	PreferredTypes []string               `protobuf:"bytes,3,rep,name=preferred_types,json=preferredTypes,proto3" json:"preferred_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_src_worker_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetJobRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GetJobRequest) GetPreferredTypes() []string {
	if x != nil {
		return x.PreferredTypes
	}
	return nil
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasJob        bool                   `protobuf:"varint,1,opt,name=has_job,json=hasJob,proto3" json:"has_job,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_src_worker_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobResponse) GetHasJob() bool {
	if x != nil {
		return x.HasJob
	}
	return false
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint32                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobType       string                 `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Seed          []byte                 `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
	TargetProfile []byte                 `protobuf:"bytes,4,opt,name=target_profile,json=targetProfile,proto3" json:"target_profile,omitempty"`
	TimeBudgetMs  uint32                 `protobuf:"varint,5,opt,name=time_budget_ms,json=timeBudgetMs,proto3" json:"time_budget_ms,omitempty"`
	RoundId       uint32                 `protobuf:"varint,6,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_src_worker_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{8}
}

func (x *Job) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *Job) GetTargetProfile() []byte {
	if x != nil {
		return x.TargetProfile
	}
	return nil
}

func (x *Job) GetTimeBudgetMs() uint32 {
	if x != nil {
		return x.TimeBudgetMs
	}
	return 0
}

func (x *Job) GetRoundId() uint32 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	JobId         uint32                 `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Result        *ResultData            `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_src_worker_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ReportResultRequest) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ReportResultRequest) GetResult() *ResultData {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResultData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hash            []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Uri             string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Signature       []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Success         bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ExecutionTimeMs uint32                 `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResultData) Reset() {
	*x = ResultData{}
	mi := &file_src_worker_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultData) ProtoMessage() {}

func (x *ResultData) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultData.ProtoReflect.Descriptor instead.
func (*ResultData) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{10}
}

func (x *ResultData) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ResultData) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResultData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ResultData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResultData) GetExecutionTimeMs() uint32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_src_worker_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_worker_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_src_worker_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ReportResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_worker_worker_proto protoreflect.FileDescriptor

const file_src_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x17src/worker/worker.proto\x12\x06worker\"n\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12>\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x1a.worker.WorkerCapabilitiesR\fcapabilities\"\x9b\x01\n" +
	"\x12WorkerCapabilities\x12\x1b\n" +
	"\tjob_types\x18\x01 \x03(\tR\bjobTypes\x12.\n" +
	"\x13max_concurrent_jobs\x18\x02 \x01(\rR\x11maxConcurrentJobs\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x04R\bmemoryMb\"k\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"\x82\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x14.worker.WorkerStatusR\x06status\"\x96\x01\n" +
	"\fWorkerStatus\x12\x1f\n" +
	"\vactive_jobs\x18\x01 \x01(\rR\n" +
	"activeJobs\x12%\n" +
	"\x0ecompleted_jobs\x18\x02 \x01(\rR\rcompletedJobs\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x02R\vmemoryUsage\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"z\n" +
	"\rGetJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12'\n" +
	"\x0fpreferred_types\x18\x03 \x03(\tR\x0epreferredTypes\"H\n" +
	"\x0eGetJobResponse\x12\x17\n" +
	"\ahas_job\x18\x01 \x01(\bR\x06hasJob\x12\x1d\n" +
	"\x03job\x18\x02 \x01(\v2\v.worker.JobR\x03job\"\xb3\x01\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\rR\x05jobId\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\fR\x04seed\x12%\n" +
	"\x0etarget_profile\x18\x04 \x01(\fR\rtargetProfile\x12$\n" +
	"\x0etime_budget_ms\x18\x05 \x01(\rR\ftimeBudgetMs\x12\x19\n" +
	"\bround_id\x18\x06 \x01(\rR\aroundId\"\x9a\x01\n" +
	"\x13ReportResultRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\rR\x05jobId\x12*\n" +
	"\x06result\x18\x04 \x01(\v2\x12.worker.ResultDataR\x06result\"\x96\x01\n" +
	"\n" +
	"ResultData\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\rR\x0fexecutionTimeMs\"L\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x94\x02\n" +
	"\rWorkerService\x12=\n" +
	"\bRegister\x12\x17.worker.RegisterRequest\x1a\x18.worker.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.worker.HeartbeatRequest\x1a\x19.worker.HeartbeatResponse\x127\n" +
	"\x06GetJob\x12\x15.worker.GetJobRequest\x1a\x16.worker.GetJobResponse\x12I\n" +
	"\fReportResult\x12\x1b.worker.ReportResultRequest\x1a\x1c.worker.ReportResultResponseB+Z)github.com/qubic/wargame-relay/src/workerb\x06proto3"

var (
	file_src_worker_worker_proto_rawDescOnce sync.Once
	file_src_worker_worker_proto_rawDescData []byte
)

func file_src_worker_worker_proto_rawDescGZIP() []byte {
	file_src_worker_worker_proto_rawDescOnce.Do(func() {
		file_src_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_worker_worker_proto_rawDesc), len(file_src_worker_worker_proto_rawDesc)))
	})
	return file_src_worker_worker_proto_rawDescData
}

var file_src_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_src_worker_worker_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: worker.RegisterRequest
	(*WorkerCapabilities)(nil),   // 1: worker.WorkerCapabilities
	(*RegisterResponse)(nil),     // 2: worker.RegisterResponse
	(*HeartbeatRequest)(nil),     // 3: worker.HeartbeatRequest
	(*WorkerStatus)(nil),         // 4: worker.WorkerStatus
	(*HeartbeatResponse)(nil),    // 5: worker.HeartbeatResponse
	(*GetJobRequest)(nil),        // 6: worker.GetJobRequest
	(*GetJobResponse)(nil),       // 7: worker.GetJobResponse
	(*Job)(nil),                  // 8: worker.Job
	(*ReportResultRequest)(nil),  // 9: worker.ReportResultRequest
	(*ResultData)(nil),           // 10: worker.ResultData
	(*ReportResultResponse)(nil), // 11: worker.ReportResultResponse
}
var file_src_worker_worker_proto_depIdxs = []int32{
	1,  // 0: worker.RegisterRequest.capabilities:type_name -> worker.WorkerCapabilities
	4,  // 1: worker.HeartbeatRequest.status:type_name -> worker.WorkerStatus
	8,  // 2: worker.GetJobResponse.job:type_name -> worker.Job
	10, // 3: worker.ReportResultRequest.result:type_name -> worker.ResultData
	0,  // 4: worker.WorkerService.Register:input_type -> worker.RegisterRequest
	3,  // 5: worker.WorkerService.Heartbeat:input_type -> worker.HeartbeatRequest
	6,  // 6: worker.WorkerService.GetJob:input_type -> worker.GetJobRequest
	9,  // 7: worker.WorkerService.ReportResult:input_type -> worker.ReportResultRequest
	2,  // 8: worker.WorkerService.Register:output_type -> worker.RegisterResponse
	5,  // 9: worker.WorkerService.Heartbeat:output_type -> worker.HeartbeatResponse
	7,  // 10: worker.WorkerService.GetJob:output_type -> worker.GetJobResponse
	11, // 11: worker.WorkerService.ReportResult:output_type -> worker.ReportResultResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_src_worker_worker_proto_init() }
func file_src_worker_worker_proto_init() {
	if File_src_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_worker_worker_proto_rawDesc), len(file_src_worker_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_worker_worker_proto_goTypes,
		DependencyIndexes: file_src_worker_worker_proto_depIdxs,
		MessageInfos:      file_src_worker_worker_proto_msgTypes,
	}.Build()
	File_src_worker_worker_proto = out.File
	file_src_worker_worker_proto_goTypes = nil
	file_src_worker_worker_proto_depIdxs = nil
}
